/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Rai4UiModule extends AbstractRai4UiModule {

	public Rai4UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
