/*
 * generated by Xtext 2.40.0
 */
package es.unican.istr.pasys.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Rai4RuntimeModule extends AbstractRai4RuntimeModule {
	
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return PropertiesConverter.class;
    }
}
