/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.pasys.xtext;

import com.google.inject.Injector;

import es.unican.istr.pasys.pasys.PasysPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Rai4StandaloneSetup extends Rai4StandaloneSetupGenerated {

	public static void doSetup() {
		new Rai4StandaloneSetupGenerated().createInjectorAndDoEMFRegistration();
	}
	
    @Override
    public void register(Injector injector) {
        super.register(injector);
        // Registrar el paquete Pasys explícitamente
        PasysPackage.eINSTANCE.eClass();
    }
}