/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.pasys.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyPasysUiModule extends AbstractMyPasysUiModule {

	public MyPasysUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
