/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Rai4StandaloneSetup extends Rai4StandaloneSetupGenerated {

	public static void doSetup() {
		new Rai4StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
