/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.pasys.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyPasysScopeProvider extends DelegatingScopeProvider {
}
