/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyPasysRuntimeModule extends AbstractMyPasysRuntimeModule {
	
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return PropertiesConverter.class;
    }

}