/*
 * generated by Xtext 2.40.0
 */
package es.unican.istr.pasys.xtext.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class Rai4ProposalProvider extends AbstractRai4ProposalProvider {
}
