/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Rai4AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/unican/istr/xtext/parser/antlr/internal/InternalRai4.tokens");
	}
}
