/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.pasys.parser.antlr;

import com.google.inject.Inject;
import es.unican.istr.pasys.parser.antlr.internal.InternalMyPasysParser;
import es.unican.istr.pasys.services.MyPasysGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyPasysParser extends AbstractAntlrParser {

	@Inject
	private MyPasysGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyPasysParser createParser(XtextTokenStream stream) {
		return new InternalMyPasysParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ComputationalSystem";
	}

	public MyPasysGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyPasysGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
