/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.pasys.ui.tests;

import com.google.inject.Injector;
import es.unican.istr.pasys.ui.internal.PasysActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyPasysUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PasysActivator.getInstance().getInjector("es.unican.istr.pasys.MyPasys");
	}

}
