/*
 * generated by Xtext 2.40.0
 */
package es.unican.istr.pasys.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRai4ScopeProvider extends DelegatingScopeProvider {
}
