/*
 * generated by Xtext 2.40.0
 */
package es.unican.istr.pasys.xtext.parser.antlr;

import com.google.inject.Inject;
import es.unican.istr.pasys.xtext.parser.antlr.internal.InternalRai4Parser;
import es.unican.istr.pasys.xtext.services.Rai4GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Rai4Parser extends AbstractAntlrParser {

	@Inject
	private Rai4GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRai4Parser createParser(XtextTokenStream stream) {
		return new InternalRai4Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ComputationalSystem";
	}

	public Rai4GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Rai4GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
