/*
 * generated by Xtext 2.35.0
 */
package es.unican.istr.pasys;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyPasysStandaloneSetup extends MyPasysStandaloneSetupGenerated {

	public static void doSetup() {
		new MyPasysStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
