/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext.ui.tests;

import com.google.inject.Injector;
import es.unican.istr.xtext.rai4.ui.internal.Rai4Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Rai4UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Rai4Activator.getInstance().getInjector("es.unican.istr.xtext.Rai4");
	}

}
