/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyPasysScopeProvider extends DelegatingScopeProvider {
}
