/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import es.unican.istr.xtext.Rai4RuntimeModule;
import es.unican.istr.xtext.Rai4StandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Rai4IdeSetup extends Rai4StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Rai4RuntimeModule(), new Rai4IdeModule()));
	}
	
}
