/*
 * generated by Xtext 2.32.0
 */
package es.unican.istr.xtext.ui;

import com.google.inject.Injector;
import es.unican.istr.xtext.rai4.ui.internal.Rai4Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Rai4ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Rai4Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Rai4Activator activator = Rai4Activator.getInstance();
		return activator != null ? activator.getInjector(Rai4Activator.ES_UNICAN_ISTR_XTEXT_RAI4) : null;
	}

}
