/*
 * generated by Xtext 2.40.0
 */
package es.unican.istr.pasys.xtext.ui.tests;

import com.google.inject.Injector;
import es.unican.istr.pasys.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Rai4UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("es.unican.istr.pasys.xtext.Rai4");
	}

}
